
import type { Metadata } from "next";
import { Inter, Istok_Web } from "next/font/google";
import "./globals.css";

const inter = Inter({ weight: '500', subsets: ["latin"] });
const IstokWeb = Istok_Web({ weight: '400', subsets: ['latin'], style: 'normal'})


export const metadata: Metadata = {
  title: "made by nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
