
import type { Metadata } from "next";
import { Inter, Istok_Web } from "next/font/google";
import "./globals.css";

// fonts
const inter = Inter({ weight: '500', subsets: ["latin"] });



export const metadata: Metadata = {
  title: "made by nextjs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
  );
}
